### ISSUE TITLE
Add more settings to the bot

### ISSUE THREAD

**Issue by V-ed** [Vhoyon/Discord-Bot#75]
After #35, some settings could be implemented into the bot's logic.

- [x] `prefix` : Changes the command prefix (_currently defaults to `!!`_) (#35)
- [x] `param_prefix` : Changes the parameters prefix (_currently defaults to `--`_) (#76)
- [x] `volume` : Changes the default volume for the bot (_currently defaults to `75`_) (#77)
    - `[value]`'s range would be between 0-100
- [x] `confirm_stop` : Changes the behavior of inputting the command `stop` with no arguments if it confirms or not (_defaults currently to `true`_) (#78)
    - `[value]` would be `true` or `false`

Also, #79.
