### ISSUE TITLE
Add an enum setting field to allow for setting choices

### ISSUE THREAD

**Issue by V-ed** [Vhoyon/Discord-Bot#88]
After the addition of Settings in #70, few fields have been added, but there is a missing `enum` field that would be great to allow only for a range of options.

#### Tasks
- [x] Create object and constructors (with _and_ without `isSorted` variable);
- [x] Add a formatter to the env variable (pipes);
- [x] Add a sorter to the choices list when specified;

---

### Create object and constructors

The field's constructor could look like this :
```java
/**
@param name SettingField's behavior of mapping this field.
@param env SettingField's behavior of handling values from the environment.
@param defaultValue Default value used for the setting.
@param othervalues Choices associated with that enum. 
*/
public EnumField(String name, String env, Object defaultValue, Object... otherValues);
```
\* _Take note here about the fact that the `defaultValue` variable shouldn't be present in `otherValues` and will be considered also like a choice - just that it's the default selected._

---

### Add a formatter to the env variable (pipes)

Now, we could ask how would the enum settings be captured from the environment file. Here's my take on this :
```
ENUM_CHOICE=one|two|three
```
Therefore, the choices for this enum would be `one`, `two` or `three`, `one` being the default.

---

That also means it would be great if a sorting algorithm would take place for the values :
1. [selected value]
2. `a`
3. `b`
4. `...`

In the example with the environment, the sorting would look like so :
1. `one`
2. `three`
3. `two`

### Create object and constructors

This sorting brings a little problem tho : maybe the dev doesn't want this sorting for his displays, or he would want to sort it himself.

### Add a sorter to the choices list when specified

Thus, I bring this new constructor (overloaded from the first) :
```java
/**
@param name SettingField's behavior of mapping this field.
@param env SettingField's behavior of handling values from the environment.
@param isSorted Boolean that tells the field if the choices should be sorted or not.
@param defaultValue Default value used for the setting.
@param othervalues Choices associated with that enum. 
*/
public EnumField(String name, String env, boolean isSorted, Object defaultValue, Object... otherValues);
```
The default value (_constructor without the `isSorted` variable_) would be to **`false`** to make it more consistent with the [WYSIWYG](https://fr.wikipedia.org/wiki/What_you_see_is_what_you_get) philosophy.

This default would keep the original
1. `one`
2. `two`
3. `three`
(order where the dev has set it) while allowing for an easier sorting mechanic.

And in the case where a dev would like to store them unsorted while getting them sorted (so he has the option to), a method to get the sorted values would be available (`getSortedValues()`?).

**Comment by V-ed** [comment]
The `sorted` behavior is not implemented in `EnumField` because there would be a mismatch between the two constructors that this issue gives as example.

I ultimately decided to go for a "new" type, `EnumSortedField`, which guess what, sorts the enums. The behavior of the `EnumSortedField` is 99% the same (it extends `EnumField` and overrides only a single method, not used in any of the logic that tells the enum its default value and etc.

Way cleaner, can't be wrong when creating this setting type, I feel like it's a good compromise.

If you got any objection to this new type, feel free to complain about it here, it _probably_ won't change though. :)
